name: Triggers Demo

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show event info
        run: echo "Triggered by ${{ github.event_name }}"
